# Generated by Django 5.2.6 on 2025-12-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_council_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpv_code', models.CharField(help_text='e.g. 45233120-6', max_length=20)),
                ('title', models.CharField(help_text='e.g. Road Resurfacing', max_length=200)),
                ('description', models.TextField()),
                ('estimated_value', models.IntegerField(help_text='The ceiling budget for this specific package')),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for Bidding'), ('REVIEW', 'Under Review'), ('CLOSED', 'Closed / Awarded')], default='OPEN', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='supply_chain.project')),
            ],
        ),
    ]
