# Generated by Django 5.2.6 on 2025-12-07 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_requirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='council',
            options={'ordering': ['name'], 'verbose_name_plural': 'Councils'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['deadline'], 'verbose_name': 'Work Package', 'verbose_name_plural': 'Work Packages'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cpv_code',
            field=models.CharField(help_text='Format: 8 digits, a hyphen, and a check digit (e.g. 45233120-6)', max_length=10, validators=[django.core.validators.RegexValidator(message='CPV code must be in the format XXXXXXXX-Y (e.g. 45233120-6)', regex='^\\d{8}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, help_text='The ceiling budget for this specific package', max_digits=12),
        ),
    ]
