# Generated by Django 5.2.6 on 2025-12-08 00:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_project_slug_alter_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['council']),
        ),
    ]
