# Generated by Django 5.2.6 on 2025-12-08 00:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_alter_council_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
    ]
