# Generated by Django 5.2.6 on 2025-12-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_alter_council_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='bamboo_standard',
            field=models.CharField(choices=[('GREEN', 'Going Green'), ('AWARE', 'Eco-Conscious'), ('LEADER', 'Climate Leader'), ('REGEN', 'Regenerative Pioneer')], default='GREEN', help_text='The sustainability rating of this council within the network.', max_length=10),
        ),
        migrations.AddField(
            model_name='council',
            name='region',
            field=models.CharField(choices=[('NE', 'North East'), ('NW', 'North West'), ('YH', 'Yorkshire and the Humber'), ('EM', 'East Midlands'), ('WM', 'West Midlands'), ('EE', 'East of England'), ('LDN', 'London'), ('SE', 'South East'), ('SW', 'South West'), ('SCT', 'Scotland'), ('WLS', 'Wales')], default='YH', max_length=5),
        ),
        migrations.AddField(
            model_name='council',
            name='sustainability_mission',
            field=models.TextField(blank=True, default='Committed to reducing carbon emissions and promoting circular economy principles in all local infrastructure projects.', help_text="The council's key sustainability quote or mission statement."),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(choices=[('LEVY', 'UK Green Levy'), ('GRANT', 'Direct Council Grant'), ('PPP', 'Private-Public Partnership'), ('LOTTERY', 'National Lottery Heritage Fund'), ('RESILIENCE', 'Climate Resilience Fund')], default='LEVY', max_length=20, verbose_name='Funding Source'),
        ),
        migrations.AddField(
            model_name='project',
            name='policy_mandate',
            field=models.CharField(choices=[('NZ30', 'Net Zero 2030'), ('BIO25', 'Biodiversity Gain 2025'), ('AIR', 'Clean Air Zone (CAZ)'), ('FHS', 'Future Homes Standard')], default='NZ30', max_length=20, verbose_name='Policy Mandate'),
        ),
        migrations.AddField(
            model_name='project',
            name='sustainability_goal',
            field=models.TextField(blank=True, default='This project aims to significantly reduce local carbon emissions and improve biodiversity.', help_text="Describe the specific ecological impact metrics (e.g., 'Reduces carbon by 40%...')."),
        ),
    ]
