# Generated by Django 5.2.6 on 2025-12-11 23:10

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_council_bamboo_standard_council_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique_with=('project',)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='supply_chain.requirement')),
            ],
        ),
    ]
