# Generated by Django 5.2.6 on 2025-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0009_requirement_slug_bid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('council', 'title'), name='unique_project_title_per_council'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_requirement_title_per_project'),
        ),
    ]
